language: node_js

node_js:
  - '10'
sudo: false

script:
  - npm test

before_deploy: npm run package
deploy:
  provider: releases
  api_key:
    secure: SnGn3aOeQYN5W7bCAbJ/p4UJfTmNPpglAS7ZDK3ceeNFTFNNscGav7iXxTR0sv6qLUj6JWTd5ZV4Czh2Tpijep5kMqgOaHdxEGzbLFsEevO+8UgB7S/uTzRbM0EBRuQkP+if9xGcR7PvgRWc1UXV1bsRl9CVXpNsbXIFhj6l/pBzp6bnfJ5vI80a+WQ3zp/tWi70sDSGorzdTCNjPuLy2kRZ/ggh2oJGLzxL3UGWjU2MdRzaOh89reQJ+HAYHIqaR1s/nOsFPJVmv1APXVvUEJJ8yNxuZUxLZtBVhUwVrywW5wx9PbifCUqO5eOd2w0Zcpq8n+QCceDhVCqi510n8BnUiBaEOHOXRi6vOEqn4ABr0dkf2bt4+ZK+Kh7mNdmNuuEdGq6l0tV8CMtcKrSSPXsju9nzuvxDk8uqWrBoqaL+A/K6feQkF/4F9dOzUX1yrmAFLyT6dDU4lj0yhrVrS2CF8HFRL8tRHkQ6d41oFhA3s6nXlsYjx9KVFm2xj4qScWEZGA8iuErbKK4NGwxd6fwTrdU40rnXKS+6NtwVTOgSxRjcVTYBDn2T0aixF2hESetfMUWLXNIECVwFmHhdoIRMsxTSiCrygfhbC+twsxKppflkWAFdfn6sm1Dmnt1hNrM7O2nyARqlt9CYb1o3kS70u6m3FiM8UdcYyAnMBaY=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    repo: jimpick/subscribed-hypercored
    node: '10'
tags: true